services:
  - type: worker
    name: ovv-discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    plan: free
    branch: main
    rootDir: .
